data <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
data1 <- data[data$Date == "1/2/2007" | data$Date == "2/2/2007",]
png(file="plot4.png")
par(mfrow=c(2,2))
plot(datetime, data1$Global_active_power, xlab="", ylab="Global Active Power", type = "l")
plot(datetime, data1$Voltage, ylab = "Voltage", type = "l")
plot(datetimes, sub1, type="n", xlab = "", ylab = "Energy sub metering")
points(datetimes, sub1, type = "l", col = "black")
points(datetimes, sub2, type = "l", col = "red")
points(datetimes, sub3, type = "l", col = "blue")
leg.name <-c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3")
legend("topright", leg.name, lty=1, col=c("black", "red", "blue"))
plot(datetime, data1$Global_reactive_power, type = "l")
dev.off()